apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello-world-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-flask
  template:
    metadata:
      labels:
        app: hello-world-flask
    spec:
      containers:
      - name: hello-world-flask
        image: dockerhub_username/hello-world-flask
        ports:
        - containerPort: 5000